eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8070
spring:
  application:
    name: school-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/VISA_SCHOOL_DB?createDatabaseIfNotExist=true
    username: root
    password: Welcome123
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQLDialect
        show-sql:true
        format_sql:true
application:
  config:
    students-url:http://localhost:8090/api/students