eureka:
  client:
    register-with-eureka: false
server:
  port: 9999
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/students/**
        - id: school-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/schools/**
